apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fastapikube-project
  labels:
    app: fastapikube
spec:
  type: LoadBalancer
  selector:
    app: fastapikube-nginx
  ports:
    - port: 80
      targetPort: 80