apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapikube-project
  labels:
    app: fastapikube
data:
  default.conf: |
    upstream fastapikube_project {
        server fastapikube-service:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://fastapikube_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }
