apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapikube-deployment
  namespace: fastapikube-project
  labels:
    app: fastapikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapikube-app
  template:
    metadata:
      labels:
        app: fastapikube-app
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:bullseye
          command: ['sh', '-c',
          'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
          do echo waiting for database; sleep 2; done;']
      containers:
        - image: damian/fastapikube
          imagePullPolicy: Never
          name: sample-container
          envFrom:
          - secretRef:
              name: fastapikube-secret
          ports:
            - containerPort: 5000
              name: fastapikube
          readinessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"