apiVersion: v1
kind: Service
metadata:
  name: fastapikube-service
  namespace: fastapikube-project
  labels:
    app: fastapikube
spec:
  selector:
    app: fastapikube-app
  ports:
    - port: 5000
      targetPort: 5000